# It is necessory to tell makefile about the current path
LOCAL_PATH := $(call my-dir)

# Shared libraries
include $(CLEAR_VARS)
LOCAL_MODULE := libigc
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libigc
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := lib/x86/libigc$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := lib/x86_64/libigc$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)
LOCAL_STRIP_MODULE := true
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libigdfcl
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libigdfcl
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := lib/x86/libigdfcl$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := lib/x86_64/libigdfcl$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)
LOCAL_STRIP_MODULE := true
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := libcommon_clang
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libcommon_clang
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := lib/x86/libcommon_clang$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := lib/x86_64/libcommon_clang$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)
LOCAL_STRIP_MODULE := true
include $(BUILD_PREBUILT)